### PR TITLE
test: test_conflict    

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ack 9626c2217cc375917a4f7dc6957b736048966250

**Comment by MarcoFalke** [comment]
nice, ack 9626c2

**Review by MarcoFalke — COMMENTED** [review]
approach nack

**Comment by vasild** [comment]
ACK 9626c2217cc375917a4f7dc6957b736048966250 NACK

**Comment by vasild** [comment]
the above comment did not change my "Concept NACK"

**Comment by vasild** [comment]
ACK 9626c2217cc375917a4f7dc6957b736048966250 even more

**Comment by MarcoFalke** [comment]
> the above comment did not change my "Concept NACK"

Yes, it is unclear how to deal with several keywords in the same comment, so only the first one is picked

**Comment by MarcoFalke** [comment]
ack

**Review by aureleoules — COMMENTED** [review]
crACK 9626c2217cc375917a4f7dc6957b736048966250

**Comment by kouloumos** [comment]
**code review ACK**

**Comment by 0xB10C** [comment]
CRACK 9626c2217cc375917a4f7dc6957b736048966250

**Pull request closed without merging**
